### ISSUE TITLE
How to preprocess CoNLL2003 de dataset?

### ISSUE THREAD

**Issue by fake-warrior8** [microsoft/vert-papers#16]
Hi, I downloaded the ECI Multilingual Text dataset from LDC and  the ner.tgz file from the [official CoNLL2003 website](https://www.clips.uantwerpen.be/conll2003/ner/). However, running bin/make.deu in the ner folder (built from ner.tgz) did not get the CoNLL2003 de dataset, it showed an error: Incorrect number of lines in data files. Could you tell me how to preprocess CoNLL2003 de dataset with the ECI dataset and ner.tgz? Thanks.

**Comment by Weile-Chen** [comment]
We didn't use the bin/make.deu to get the dataset. Maybe you can implement code to preprocess the raw text like the data example in our code.

**Comment by iofu728** [comment]
> Hi, I downloaded the ECI Multilingual Text dataset from LDC and the ner.tgz file from the [official CoNLL2003 website](https://www.clips.uantwerpen.be/conll2003/ner/). However, running bin/make.deu in the ner folder (built from ner.tgz) did not get the CoNLL2003 de dataset, it showed an error: Incorrect number of lines in data files. Could you tell me how to preprocess CoNLL2003 de dataset with the ECI dataset and ner.tgz? Thanks.

Hi @fake-warrior8, we use the official data preprocess script. In your case, you should follow the official preprocess [`README`](https://www.clips.uantwerpen.be/conll2003/ner/000README) file. And put the raw text files of German in the `ner/` folder. 
Due to the copyright, we can't share the data set with you. If you have any questions, please contact us by issue or email.
