### ISSUE TITLE
How to deal with labels that don't appear in N-way labels

### ISSUE THREAD

**Issue by Quang-elec44** [microsoft/vert-papers#36]
Hi, I have a question? If you choose N classes, e.g PER, LOC, ORG, and then when a sample that contains another tag, e.g MISC, is randomly chosen (a sequence contains both PER and MISC), how do you deal with this?

**Comment by iofu728** [comment]
Hi @Quang-elec44, there is a set of standardized procedures for the N-way K-shot setting. The Few-NERD replace the other entity type with "O", you can find the detail in the 6.2 section of [their paper](https://arxiv.org/pdf/2105.07464.pdf). And there's no such problem due to Cross-Dataset using different domain datasets.
